DROP SCHEMA IF EXISTS ENVIOVITAL CASCADE;

CREATE SCHEMA IF NOT EXISTS ENVIOVITAL;

CREATE TABLE ENVIOVITAL.PROVINCIA(
	ID SERIAL NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50)
);

CREATE TABLE ENVIOVITAL.EVENTO(
ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(500),
ACTIVO BOOLEAN,
PROVINCIA SMALLINT NOT NULL
);

CREATE TABLE ENVIOVITAL.CONDUCTOR(
ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDOS VARCHAR(150),
DNI CHAR(9),
DIRECCION VARCHAR (500),
TELEFONO VARCHAR(15),
USUARIO INT NOT NULL
);

CREATE TABLE ENVIOVITAL.USUARIO(
ID SERIAL NOT NULL PRIMARY KEY,
USERNAME VARCHAR(25),
PASSWORD VARCHAR(500),
EMAIL VARCHAR(50),
ROL INT NOT NULL
);

CREATE TABLE ENVIOVITAL.ALMACEN(
ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(500),
ACTIVO BOOLEAN,
PROVINCIA SMALLINT NOT NULL,
USUARIO INT NOT NULL
);

CREATE TABLE ENVIOVITAL.VEHICULO(
ID SERIAL NOT NULL PRIMARY KEY,
MARCA VARCHAR(50),
MODELO VARCHAR(500),
MATRICULA VARCHAR(10), -- COMENTAR ESTO A LUIS A, PONE 500 PERO EN VD UNA MATRICULA ES CORTA
CONDUCTOR INT NOT NULL,
TIPO_VEHICULO INT NOT NULL
);

CREATE TABLE ENVIOVITAL.TIPOVEHICULO(
ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(500)
);



CREATE TABLE ENVIOVITAL.CONDUCTORALMACEN (
ID SERIAL NOT NULL PRIMARY KEY,
ALMACEN INT NOT NULL,
CONDUCTOR INT NOT NULL
);


ALTER TABLE ENVIOVITAL.EVENTO ADD CONSTRAINT FK_EVENTO_PROVINCIA FOREIGN KEY (PROVINCIA) REFERENCES ENVIOVITAL.PROVINCIA(ID);
ALTER TABLE ENVIOVITAL.ALMACEN ADD CONSTRAINT FK_ALMACEN_PROVINCIA FOREIGN KEY (PROVINCIA) REFERENCES ENVIOVITAL.PROVINCIA(ID);
ALTER TABLE ENVIOVITAL.ALMACEN ADD CONSTRAINT FK_ALMACEN_USUARIO FOREIGN KEY (USUARIO) REFERENCES ENVIOVITAL.USUARIO(ID);
ALTER TABLE ENVIOVITAL.CONDUCTOR ADD CONSTRAINT FK_CONDUCTOR_USUARIO FOREIGN KEY (USUARIO) REFERENCES ENVIOVITAL.USUARIO(ID);
ALTER TABLE ENVIOVITAL.VEHICULO ADD CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY (CONDUCTOR) REFERENCES ENVIOVITAL.CONDUCTOR(ID);
ALTER TABLE ENVIOVITAL.VEHICULO ADD CONSTRAINT FK_VEHICULO_TIPOVEHICULO FOREIGN KEY (TIPO_VEHICULO) REFERENCES ENVIOVITAL.TIPOVEHICULO(ID);
ALTER TABLE ENVIOVITAL.CONDUCTORALMACEN ADD CONSTRAINT FK_CONDUCTORALMACEN_CONDUCTOR FOREIGN KEY (CONDUCTOR) REFERENCES ENVIOVITAL.CONDUCTOR(ID);
ALTER TABLE ENVIOVITAL.CONDUCTORALMACEN ADD CONSTRAINT FK_CONDUCTORALMACEN_ALMACEN FOREIGN KEY (ALMACEN) REFERENCES ENVIOVITAL.ALMACEN(ID);
    





